### PR TITLE
Place include .hpp headers alphabetically

### PR DESCRIPTION
**Pull request by kostis**
Their proper ordering was missed when the tests files were cleaned up.

### CODE REVIEW

**Comment by ioanev** [comment]
> **Note**
The top-level ArgoDSM header was purposely left to precede the rest of the headers in that group.

**Review by lundgren87 — APPROVED** [review]
Alphabetical order makes sense in order to eventually automate checking.

**Comment by kostis** [comment]
If there are reasons to include header files in some specific order, then we should either find some alternative (e.g. include `argo.hpp` in the other header files that need it) or, of these reasons are very good ones, explicitly document them (perhaps only in some comment) and add a LINT exception.

Leaving such _intentions_ undocumented is not good for understandability and maintenance of the code.  In this particular case, there does not appear to be any good reason to not stick to alphabetic order.  If @ioanev knows such a a reason, perhaps we can document it.

**Comment by ioanev** [comment]
Wrong judgement from my side, and I should have mentioned this as a note in the relevant PR's description.
This was easy miss in the review.
Please go ahead.

> **Note**
The change might also need to be applied here:

https://github.com/etascale/argodsm/blob/2602a69da6f682696a4e012cd91d614671669ac0/src/argo.cpp#L7-L14

**Comment by kostis** [comment]
> > Note
> > The change might also need to be applied here:
> 
> https://github.com/etascale/argodsm/blob/2602a69da6f682696a4e012cd91d614671669ac0/src/argo.cpp#L7-L14

This is a special case.  A `.cpp` file should _always_ include its corresponding `.hpp` (`.h`) file first.

**Pull request merged**
